config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'foots#index'
  resources :foots, only: [:index, :create, :new, :show] do
    resources :reviews, onry: [:index, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ascore.rb
class Ascore < ActiveHash::Base
  self.data = [
    { id: 0, name:  '--' },
    { id: 1, name:  '1' },
    { id: 2, name:  '2' },
    { id: 3, name:  '3' },
    { id: 4, name:  '4' },
    { id: 5, name:  '5' },
    { id: 6, name:  '6' },
    { id: 7, name:  '7' },
    { id: 8, name:  '8' },
    { id: 9, name:  '9' },
    { id: 10, name: '10' },
    { id: 11, name: '11' }
  ]
end

app/models/bscore.rb
class Bscore < ActiveHash::Base
  self.data = [
    { id: 0, name:  '--' },
    { id: 1, name:  '1' },
    { id: 2, name:  '2' },
    { id: 3, name:  '3' },
    { id: 4, name:  '4' },
    { id: 5, name:  '5' },
    { id: 6, name:  '6' },
    { id: 7, name:  '7' },
    { id: 8, name:  '8' },
    { id: 9, name:  '9' },
    { id: 10, name: '10' },
    { id: 11, name: '11' }
  ]
end

app/models/foot.rb
class Foot < ApplicationRecord
  belongs_to :user, optional: true
  has_many_attached :images
  has_many :reviews, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :ascore
  belongs_to_active_hash :bscore

  with_options presence: true do
    validates :images
    validates :ateam
    validates :one_member
    validates :two_member
    validates :three_member
    validates :four_member
    validates :five_member
    validates :six_member
    validates :seven_member
    validates :eight_member
    validates :nine_member
    validates :ten_member
    validates :eleven_member
    validates :bteam
    validates :aone_member
    validates :atwo_member
    validates :athree_member
    validates :afour_member
    validates :afive_member
    validates :asix_member
    validates :aseven_member
    validates :aeight_member
    validates :anine_member
    validates :aten_member
    validates :aeleven_member
  end

  with_options numericality: { other_than: 0 } do
    validates :ascore_id
    validates :bscore_id
  end

  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f
    end
  end

  def review_score_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f * 100 / 5
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :foot

  validates :score, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :foots
  has_many :reviews, dependent: :destroy

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,}+\z/i }

  validates :nickname, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index]
  before_action :configre_permitted_parameters, if: :devise_controller?

  def configre_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/foots_controller.rb
class FootsController < ApplicationController
  before_action :set_foot, only: [:edit, :update, :show]
  before_action :authenticate_user!, only: [:show]

  def index
    @foots = Foot.all.order('created_at DESC')
    
  end

  def new
    @foot = Foot.new
  end

  def create
    @foot = Foot.new(foot_params)
    if @foot.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    redirect_to root_path if @foot.destroy
  end

  def edit
  end

  def update
    if @foot.update(foot_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @review = Review.new
  end

  private

  def foot_params
    params.require(:foot).permit(:ateam, :ascore_id, :bteam, :bscore_id, :one_member, :two_member, :three_member, :four_member, :five_member, :six_member, :seven_member, :eight_member, :nine_member, :ten_member, :eleven_member, :aone_member, :atwo_member, :athree_member, :afour_member, :afive_member, :asix_member, :aseven_member, :aeight_member, :anine_member, :aten_member, :aeleven_member, images: []).merge(user_id: current_user.id)
  end

  def set_foot
    @foot = Foot.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @foot = Foot.find(params[:foot_id])
    @reviews = @foot.reviews
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to foot_reviews_path(@review.foot)
    else
      @foot = Foot.find(params[:id])
      render 'foot/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:foot_id, :score, :content )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foots_helper.rb
module FootsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/foots/index.html.erb
<%= render "shared/header" %>
<div class='main'>
 
  <div class='m-size'>
  <div class='title-contents'>
      <h2 class='service-title'>
        FootScoring
      </h2>
      <p class='service-explain'>
        ユーザー同士で
      </p>
      <p class='service-explain'>
        試合を採点しよう！！！
      </p>
  </div>
  </div>

  <div class='item-contents'>
      <h2 class='title'>最新情報</h2>
      <%= link_to '試合結果', "#", class: "subtitle" %>
  </div>

  <div class= 'game'>
  <% @foots.each do |foot| %>
    <div class='sss'>
    <div class='time'>
      <%= foot.created_at.to_s(:datetime_jp) %>
    </div>
    <div class='foot-img-content'>
      <% foot.images.each do |image| %>
      <%= image_tag image.variant(resize: '100x100'), class: 'm-images'%>
      <% end %> 
    </div>

    <%= link_to foot_path(foot.id) do %>
    <div class='team-name'>
      <div class='item-name'>
        <%= foot.ateam %>
      </div>
      <div class='ttt'>VS</div>
      <div class='item-name'>
        <%= foot.bteam %>
      </div>
    </div>
    <% end %>
    <div class='foot-name'>
      <div class='away-name'>
        <%= foot.ascore_id %>
      </div>
      <h2 class='yyy'>ー</h2>
      <div class='away-name'>
        <%= foot.bscore_id %>
      </div>
    </div>
    </div>
  <% end %>
  </div>
</div>







<% if user_signed_in? %>
  <% if current_user == @user || current_user.admin? %>
    <%= link_to new_foot_path do%> 
    <div class='purchase-btn'>
      <span class='purchase-btn-text'>結果投稿</span>
    <%= image_tag 'soccer.png' , size: '185x50' ,class: "purchase-btn-icon" %>
    </div>
    <% end %>
  <% end %>
<% end %>

app/views/foots/new.html.erb
<%= render "shared/header" %>
<div class="items-sell-contents">

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">試合結果を入力</h2>
    <%= form_with model: @foot, url: foots_path, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# チーム画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'foot[images][]', id:"foot_image" %>
      </div>
        <div id="image-list"></div>
    </div>

    <% @foot.images.each do |image| %>
    <%= image_tag foot.image, class: 'images' %>
    <% end %>
    <%# /出品画像 %>
    <%# チーム名 %>
    <div class="new-items">
      <div class="weight-bold-text">
        ホームチーム名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :ateam, class:"items-text", id:"item-name", placeholder:"チーム名（必須 40文字まで)", maxlength:"40" %>
    </div>

    <h2 class='www'>メンバー登録</h2>

    <div class="new-items">
      <div class="weight-bold-text">
        GK
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :one_member, class:"items-text", id:"item-name", placeholder:"フルネーム" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        DF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :two_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        DF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :three_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        DF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :four_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        DF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :five_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        MF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :six_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        MF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :seven_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        MF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :eight_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        MF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :nine_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        FW
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :ten_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        FW
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :eleven_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    

    <div class="items-detail">
      <div class="form">
        <div class="weight-bold-text">
          点数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:ascore_id, Ascore.all, :id, :name, {}, {class:"genre-select"})  %>
      </div>
    </div>


    <%# チーム名 %>
    <div class="new-items">
      <div class="weight-bold-text">
        アウェイチーム名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :bteam, class:"items-text", id:"item-name", placeholder:"チーム名（必須 40文字まで)", maxlength:"40" %>
    </div>
    <%# チーム名 %>

    <h2 class='www'>メンバー登録</h2>


    <div class="new-items">
      <div class="weight-bold-text">
        GK
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :aone_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        DF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :atwo_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        DF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :athree_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        DF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :afour_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        DF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :afive_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        MF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :asix_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        MF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :aseven_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        MF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :aeight_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        MF
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :anine_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        FW
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :aten_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        FW
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :aeleven_member, class:"items-text", id:"item-name", placeholder:"フルネーム", maxlength:"40" %>
    </div>

    <%# 点数選択 %>
    <div class="items-detail">
      <div class="form">
        <div class="weight-bold-text">
          点数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:bscore_id, Bscore.all, :id, :name, {}, {class:"genre-select"})  %>
      </div>
    </div>


    <div class="sell-btn-contents">
      <%= f.submit "試合結果表示" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  
  <% end %>

</div>

app/views/foots/show.html.erb
<%= render "shared/header" %>

<div class='show-back'>

<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
          <div class="card mb-6">
            <header class="card-header">
              <div class="scroll">
                <span><%= @foot.ateam %>VS<%= @foot.bteam %></span>
              </div>
            </header>
            <div class="card-content">
              <div class="content">
                <div class="content average-score">
                  <div class="star-rating mb-2">
                    <div class="star-rating-front" style="width: <%= @foot.review_score_percentage %>%">★★★★★</div>
                    <div class="star-rating-back">★★★★★</div>
                  </div>
                  <div class="average-score-display ml-3 pt-2">
                    <%= @foot.avg_score %>点（<%= @foot.reviews.count %>件の採点）
                  </div>
                </div>
              </div>
            </div>
            <footer class="card-footer">
              <%= link_to foot_reviews_path(@foot), class: "button card-footer-item" do %>
                レビューを見る
              <% end %>
              <%= link_to foot_path(@foot), class: "button card-footer-item" do %>
                レビューを書く
              <% end %>
            </footer>
        </div>

<%= render 'reviews/form', review: @review, foot: @foot %>
<div class='iciran'>
<br>
<br>
<table>
  <caption><%= @foot.ateam %></caption>
  <thead>
    <tr><th><div class='poji'>ポジション</div></th><th><div class='poji'>メンバー</div></th></tr>
  </thead>
  <tbody>
    <tr><td><a href="index">GK</a></td><td><%= @foot.one_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.two_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.three_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.four_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.five_member %></td></tr>
    <tr><td><a href="index">GK</a></td><td><%= @foot.six_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.seven_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.eight_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.nine_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.ten_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.eleven_member %></td></tr>
  </tbody>
</table>
<br>

<br>
<br>
<table>
  <caption><%= @foot.bteam %></caption>
  <thead>
    <tr><th><div class='poji'>ポジション</div></th><th><div class='poji'>メンバー</div></th></tr>
  </thead>
  <tbody>
    <tr><td><a href="index">GK</a></td><td><%= @foot.aone_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.atwo_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.athree_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.afour_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.afive_member %></td></tr>
    <tr><td><a href="index">GK</a></td><td><%= @foot.asix_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.aseven_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.aeight_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.anine_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.aten_member %></td></tr>
    <tr><td><a href="index">DF</a></td><td><%= @foot.aeleven_member %></td></tr>
  </tbody>
</table>
<br>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scoring</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
  </head>

  <body>
  <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<p class="is-size-4 md-3">採点する</p>

<div class="rating-box mt-3">
  <%= form_with model: review, url: foot_reviews_path(foot), local: true do |f| %>
    <div class="main-rating">
      <div class="ratings mb-3">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>/5</div>
    </div>
    <%= f.hidden_field :foot_id, value: foot.id %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <%= f.text_field :content, class: "textarea" %>
    <%= f.submit "保存", class: "button mt-3" %>
    <%= link_to "他のレビューを見る", foot_reviews_path(foot), class: "button light ml-3 mt-3" %>
  <% end %>
</div>

app/views/reviews/index.html.erb
<%= render "shared/header" %>


<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @foot.ateam %>VS<%= @foot.bteam %>
            </p>
          </header>
          <div class="card-content">
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @foot.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @foot.avg_score %>点（<%= @foot.reviews.count %>件の採点）
              </div>
            </div>
          </div>
        </div>
        <table class="table is-fullwidth has-text-centered">
          <thead>
            <tr>
              <th>ユーザー</th><th>点数</th><th>内容</th>
            </tr>
          </thead>
          <tbody>
            <% @reviews.each do |review| %>
              <tr>
                <td><%= review.user.nickname %></td>
                <td><%= review.score %></td>
                <td><%= review.content %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
          <%=link_to 'もどる', foot_path(@foot.id), class:"member" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
 
  <div class='kkk'>
  <%= link_to root_path do%> 
  <span class="shadow">FootScoring</span>
  <% end %>
  <div class='nav'>
    <div class='lists-right'>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <%= link_to current_user.nickname, root_path, class: "user-nickname"  %>
          <%= link_to '退出', destroy_user_session_path, method: :delete, class: "logout"  %>
        </div> 
      <% else %>
        <div class="grid-6">
          <%= link_to '入室', new_user_session_path, class: "login" %>
          <%= link_to '登録', new_user_registration_path, class: "sign_up" %>
        </div>
      <% end %>
    </div>
  </div>
  </div>
</header>